### ISSUE TITLE
Elevation data in API

### ISSUE THREAD

**Issue by sckott** [ropensci/rredlist#15]
coming soon ...

**Comment by maelle** [comment]
What does elevation mean here?

**Comment by matthewlewis896** [comment]
Can you not already pull down elevation data using rl_search?

e.g.
library(rredlist)
my.search<-rl_search(id=my.species.id, key=my.api.key)
elevation.upper<-my.search$result$elevation_upper
elevation.lower<-my.search$result$elevation_lower

**Comment by sckott** [comment]
thanks for the note @matthewlewis896 - i can't remember now what this was about, perhaps there was going to be a new API route at some point, but seems like it won't happen if it was going to. 

You're right you can get via rl_search, closing this
