### ISSUE TITLE
Please add Plant Growth Form to rredlist

### ISSUE THREAD

**Issue by stevenpbachman** [ropensci/rredlist#20]
Thanks for developing ‘rredlist’ - finding it such a useful package. The IUCN API has now been updated to include the Plant Growth Form field. Is it possible to include this in the next update of rredlist please?

http://apiv3.iucnredlist.org/api/v3/docs#growth-forms

Thanks

Steve

**Comment by sckott** [comment]
can do

**Comment by sckott** [comment]
@stevenpbachman reinstall `devtools::install_github("ropensci/rredlist")`
