### ISSUE TITLE
Add a vignette

### ISSUE THREAD

**Issue by sckott** [ropensci/rredlist#24]
This package needs more documentation!  Help out the community by contributing a vignette. If you don't know what a vignette is, check out http://r-pkgs.had.co.nz/vignettes.html for an introduction.  

If you aren't sure how to contribute on github checkout https://github.com/ropensci/rredlist/blob/master/.github/CONTRIBUTING.md 

Keep in mind our code of conduct https://github.com/ropensci/rredlist/blob/master/CONDUCT.md

**Comment by mairindeith** [comment]
Hey! I'd like to help out - I'm new to both vignettes and navigating with APIs, but am hoping to wrangle both and this would be a good kick-in-the-rear to get on it. 

Let me know how I can help! :smile:

**Comment by sckott** [comment]
hi 👋 yes!  

have you made a vignette in an R package before? let me know either way then we can proceed from there.

**Comment by mairindeith** [comment]
Not yet, but I've read over Hadleys' guide and am quite comfortable using
Markdown.

**Comment by sckott** [comment]
let's make sure we're all set on the mechanics in the other repo first, then we can proceed with this one
