### ISSUE TITLE
Metadata function

### ISSUE THREAD

**Issue by arw36** [ropensci/rredlist#28]
Would be extremely helpful if there was a searchable metadata file that gives all options of variables. These documents tend to be buried in the redlist API host website or in pdf format. For instance. For "threats" would be great to upload these documents as a reference table. 
[IUCN_threats-classification_2012.pdf](https://github.com/ropensci/rredlist/files/1921479/IUCN_threats-classification_2012.pdf)
[IUCN_dec_2012_guidance_on_threat_impact_scoring.pdf](https://github.com/ropensci/rredlist/files/1921480/IUCN_dec_2012_guidance_on_threat_impact_scoring.pdf)

**Comment by sckott** [comment]
thanks for this @arw36 

what do you mean "all options of variables" . What variables? and what options?

**Comment by arw36** [comment]
For instance, when you run `rl_threats()` you will get a list of the relevant threats (variable = title). Would be nice to have the reference sheet of possible threat titles in a metadata sheet. Example is the Timing variable in the Threat Impact with options: 

- Only in the past and unlikely to return
- In the past but now suspended and likely to return
- Ongoing
- Only in the future
- Unknown

The Threat classification is listed at  http://www.iucnredlist.org/technical-documents/classification-schemes/threats-classification-scheme rather than in the API site specifically. It seems for each table you need to dig deep in IUCN to find the metadata, so would be ideal for the R package to have a place for this.

**Comment by sckott** [comment]
thanks for clarification.  Would you mind helping me make a list of the functions that could use links to further documentation?

**Comment by arw36** [comment]
Sure thing, there's actually only three that I found with API access. 
[rredlist_metadata.xlsx](https://github.com/ropensci/rredlist/files/1934946/rredlist_metadata.xlsx)

**Comment by sckott** [comment]
just re-uploading in a more universal format

[file.txt](https://github.com/ropensci/rredlist/files/1948012/file.txt)

**Comment by sckott** [comment]
hi @arw36 - sorry about the delay!  Do you think you have time/interest to send a pull request with the changes we've discussed here? if not no worries, let me know either way

**Comment by arw36** [comment]
I’ll take a stab at this and let you know this weekend.

**Comment by sckott** [comment]
thanks @arw36 😸
