### ISSUE TITLE
Package with a similar name

### ISSUE THREAD

**Issue by maelle** [ropensci/rredlist#30]
Maybe the README&vignette could include a small sentence about [`redlistr`](https://github.com/red-list-ecosystem/redlistr)?

**Comment by sckott** [comment]
perhaps, AFAICT it doesn't have any overlap functionality, right?

**Comment by maelle** [comment]
No it doesn't but it could lead to confusion (I was confused this morning 🙈 ), hence my suggesting to mention it :-) Plus it's related to IUCN Red List too so maybe someone could find this README and actually look for functionalities covered by the other package. (I opened a similar issue in their repo)

**Comment by MirzaCengic** [comment]
+1 for mentioning the name similarity. I've worked with both packages so I know the functions, but still it took me a moment just now looking for `redlistr::rl_habitats()` function. 
For someone not aware of this it might a bigger issue than changing where the extra "r" goes :)

**Comment by sckott** [comment]
okay, will do

**Comment by sckott** [comment]
thanks @arw36 

> redlistr is the internally used package by IUCN

so it's not meant for others to use then? or it is?

**Comment by arw36** [comment]
Perhaps it could be... this is mainly for calculating spatial variables, which I don't believe their underlying data is publically available. So if someone has their own data the could use the same framework as IUCN - but I don't think its meant to be reproducible publically. That said I haven't used this package, so not the best person to ask. I had also been confused about this a few months back.
