### ISSUE TITLE
API vs website

### ISSUE THREAD

**Issue by maelle** [ropensci/rredlist#35]
Probably a stupid question but why is there http://www.iucnredlist.org/details/22706233/0 while `rredlist::rl_search("seleucidis melanoleuca")` returns no result?

**Comment by sckott** [comment]
i suspect because the website doesn't use their API

**Comment by maelle** [comment]
too bad, I saw a few other examples, less data accessible via the API 😭

**Comment by sckott** [comment]
yeah, sorry about that 😢

**Comment by maelle** [comment]
no problem :wink: Is this discrepancy noted in the docs btw?

**Comment by sckott** [comment]
might be, will check
