### ISSUE TITLE
How exactly were the vcr cassettes generated?

### ISSUE THREAD

**Issue by maelle** [ropensci/rredlist#36]
I think I'm looking for info about how to set up testing with `vcr`, do you create each cassette by hand etc.

**Comment by sckott** [comment]
no, cassettes are created by running tests with vcr in use. so you never touch the cassette files unless you want to delete them - and if you delete they will be re-created when you run tests again

**Comment by maelle** [comment]
aaaah ok like ``vdiffr` does (for testing plots, nothing to do with it, but now I see).

**Comment by sckott** [comment]
right
