### ISSUE TITLE
API vs Website again

### ISSUE THREAD

**Issue by electricquad** [ropensci/rredlist#39]
I see the previous discussion on the API vs Website issue. I am encountering that as well. For the order I am looking at, we pulled country level occurrence data from the website and from the API. API returns a lower species count in most cases.

For example: "Nyassunio nyassaensis" occurs in 3 countries according to the website while 
`rl_occ_country("Nyassunio nyassaensis",key=IUCN_REDLIST_KEY) `
returns no occurrences. 

I guess I just want to understand why the website and API differ?

**Comment by sckott** [comment]
thanks for your question. I don't know for sure, but i suspect because their API is NOT used in their website, so the website is pulling from a different data source than the API exposes. 

Ill ask and see if I get a response at least for this example

**Comment by electricquad** [comment]
Thanks, I can provide a more comprehensive example and comparison dataset for the order Unionoida for all countries off the website if that will help. The issue is the same if you query countries (e,g, Malawi - 8 species of Unionoida on the website, 0 on the API)

**Comment by electricquad** [comment]
Ok, I guess I just solved the problem. Doing a download of the unionoida results through the website, with all of the options checked in my profile seems to get me what I want.

**Comment by sckott** [comment]
Glad you solved your problem! Hoping to hear back soon and I'll let you know
