### ISSUE TITLE
missing species from rl_sp_country output

### ISSUE THREAD

**Issue by arw36** [ropensci/rredlist#46]
Why are certain species missing from this output of species list by country despite IUCN having maps that show presence? Using foxes in ukraine as an example: 

```
ua_species <- rl_sp_country("ua", key = token)
"Vulpes vulpes" %in% ua_species$result$scientific_name
```
This yields false, but should be true based on viewing the IUCN spatial maps.  https://www.iucnredlist.org/species/23062/46190249

This may be same issue as #39

**Comment by sckott** [comment]
Thanks for the issue @arw36 

I do see that Ukraine is in the map of the range for that taxon, but If i look at the geographic range section of that page https://www.iucnredlist.org/species/23062/46190249#geographic-range it doesn't list Ukraine in the list of countries - so maybe the results - Or do you mean that that taxon is in Ukraine in the iucn maps https://www.iucnredlist.org/resources/spatial-data-download ?

**Comment by arw36** [comment]
Ah, I meant Ukraine is a location on the map (and mammal guides for the country), so I guess this is an omission in the text section on IUCN side not rredlist that I can manually fix in my analysis. What's best practice for contacting IUCN about page errors: contact the assessor?  the authority? IUCN SSC CANID SPECIALIST GROUP in this case.

**Comment by sckott** [comment]
I don't know who to contact about this. On the iucn site there's an email under contact us or give feedback - no idea if they'll respond though

**Comment by arw36** [comment]
Ah kay. I sent the an email to redlist@iucn.org and the canid group. Worth a try I guess.
