### ISSUE TITLE
Collecting species by population trend?

### ISSUE THREAD

**Issue by lime-n** [ropensci/rredlist#48]
Hi, 

I was wondering if it were possible to collect species by population trend? i.e. decreasing, increasing, stable or unknown?

**Comment by ingomiller** [comment]
Any updates on this?

**Comment by willgearty** [comment]
Sorry for the delay on this @lime-n and @ingomiller. I took over maintenance of this package late last year and haven't had a chance to look into this issue. Hopefully I'll have some free time soon.

**Comment by willgearty** [comment]
From a quick glance at the Red List API, this does not currently seem possible.

**Comment by awpark** [comment]
How about if you used something like:

x <- rl_narrative('Fratercula arctica', parse = FALSE, key=PUT YOUR TOKEN HERE)

then

x$result[[1]]$populationtrend

**Comment by willgearty** [comment]
Just wanted to report that this is now a valid query in the new IUCN API, and is now a function in the development version of `rredlist`. Feel free to give it a try and let me know what you think!
```r
remotes::install_github("ropensci/rredlist@api_v4")
```
