### ISSUE TITLE
New Maintainer Wanted :-)

### ISSUE THREAD

**Issue by maelle** [ropensci/rredlist#49]
Or new maintainer team. :smile_cat: 

If you're interested, please comment in the issue.
For more info, see
- [our guidance on Changing package maintainers](https://devguide.ropensci.org/changing-maintainers.html);
- [our Package Curation Policy](https://devguide.ropensci.org/curationpolicy.html).

**Comment by maelle** [comment]
Cc @zachary-foster as this package is a dependency of taxize.

**Comment by willgearty** [comment]
I may be interested, I've used the package before and have experience maintaining packages.

**Comment by maelle** [comment]
Thanks a ton @willgearty!

I've gone ahead and sent you an invitation to the GitHub organization and to a team with admin access with this repository. Note that you'll need to have enabled two-factor authentication for your GitHub account, see https://ropensci.org/blog/2022/05/16/requiring-2fa-for-the-ropensci-github-organization/

Please ping me here or via `maelle@ropensci.org` if you have any question (I don't look at messages every day). You could also join our friendly Slack workspace where there is a #package-maintenance channel. What email address should our community manager @yabellini use to send you an invitation?

Please add yourself to the DESCRIPTION file with the role `c("aut", "cre")` and make @sckott just `"aut"` to officially register the maintainer change.

Thanks again and see you around!

**Comment by willgearty** [comment]
DESCRIPTION file updated, thanks!
@yabellini, please send the slack invitation to willgearty@gmail.com.

**Comment by yabellini** [comment]
Invite sent!
