### ISSUE TITLE
Issue with downloading updated IUCN data (2023-1)

### ISSUE THREAD

**Issue by Gopal-Murali** [ropensci/rredlist#54]
Hello,
The rl_sp(all = TRUE) function returns the previous version’s data (153,732 species). But the total assessed IUCN species count in the recent update (2023-1; December 11 2023 release) appears to be 157,190 (according to rl_sp_count).

I am in need of habitat and threat data for the 2023-1 version, but without the IUCN species names, I could not use the rl_habitats function to retrieve the updated information. 

Is there an alternative approach to access the updated 2023-1 version? 

Thank you,
Gopal 

```r

```
</details>

**Comment by simon-tarr** [comment]
Sorry folks, I've only just seen this. The counts were out due to a caching issue on the database after the 2023-1 update. We flushed the cache and numbers should be reporting correctly now.

The v4 API is coming along nicely, we're nearly ready for beta testers (hopefully in the next week or two)
