### ISSUE TITLE
Collate subheading information from Habitat & Ecology

### ISSUE THREAD

**Issue by arw36** [ropensci/rredlist#55]
I suspect that by [Red List API](https://apiv3.iucnredlist.org/api/v3/docs), this does not currently seem possible. But there are several subheadings in the "Habitat and Ecology" section that do not appear accessible via the package, when downloading rl_narrative or rl_search. Particularly: SYSTEM, HABITAT TYPE, GENERATION LENGTH (YEARS), CONGREGATORY, MOVEMENT PATTERNS, CONTINUING DECLINE IN AREA, EXTENT AND/OR QUALITY OF HABITAT

Has this come up before?

**Comment by willgearty** [comment]
Thanks for opening an issue!

For the SYSTEM field, there should be three "_system" columns in the return of `rl_search()`. Habitat information is returned as part of `rl_narrative()`, and for more specific habitat information, you can use `rl_habitat()`.

Unfortunately, I don't see a way to access the other fields that you mentioned from the Red List API, but it's possible that some of these fields would be possible to access via the [Red List Spatial API](https://apiv3.iucnredlist.org/spatial).

**Comment by willgearty** [comment]
It's also possible that these fields will be accessible when the new version of the API is released.
