### ISSUE TITLE
Where can I find the IUCN categories info (e.g., CR, EN, VU)?

### ISSUE THREAD

**Issue by XuWeiEvo** [ropensci/rredlist#61]
If I need a detailed assessment of IUCN categories, should I use other tools for extraction, or are there tools available within rredlist? Thank you!

**Comment by willgearty** [comment]
Could you provide more information about the kind of information that you are interested in? Basically, if you can see the information on an IUCN species page (e.g., https://www.iucnredlist.org/species/57334/178948447), you can retrieve that information with rredlist. Note that most of the functions (in the development version of the package) only return basic information about an assessment, but if you retrieve the details of a single assessment (e.g., `rl_assessment()`), that will return a LOT of data, including all of the information **that is available** for the category assessment. If you don't see the information that you are interested in in the return of `rl_assessment()`, then it is not available via the IUCN Red List API and you will need to look elsewhere.

**Comment by XuWeiEvo** [comment]
Thank you for your reply! I require the IUCN category information for specific species such as CR, EN, VU, and LC. As I understand it, this information is stored in the "assessment." Do I understand correctly?

**Comment by XuWeiEvo** [comment]
Thank you so much for your help!
